### ISSUE TITLE
lock users

### ISSUE THREAD

**Issue by chris-golden** [ryandaniels/ansible-role-create-users#15]
Hi there,

did you get this snippet to work?

```
- name: Lock users | Lock password & ssh key authentication
  user:
    name: "{{ item.0.username }}"
    expires: 0 #lock account if not locked
    #  command: change -E 0 {{ item.0.username }} #Alternative lock password & ssh key authentication
    #  register: user_results
    when: item.0.user_state == 'lock' and item.1 in groups
    with_subelements:
      - "{{ users }}"
      - servers
    loop_control:
      label: "username: {{ item.0.username }}, user_state: {{ item.0.user_state }}"
```
