### ISSUE TITLE
Removing a group from the "servers" list does not delete the user from those servers

### ISSUE THREAD

**Issue by vuzdemav** [ryandaniels/ansible-role-create-users#18]
Suppose there is a user `joebloggs` with the following permissions:
```yaml
- username: joebloggs
  user_state: present
  # ...
  servers:
    - www-dev
    - www-prod
```
Running this role will create the user on the "www-dev" and "www-prod" hosts.

Now suppose that the user should no longer have access to production hosts, so the users entry is changed to:
```yaml
- username: joebloggs
  user_state: present
  # ...
  servers:
    - www-dev
```
(i.e. `www-prod` is removed). The `joebloggs` user will not be deleted from existing `www-prod` hosts.
